README.md
Adding listenAddress and API settings in Example Configuration
=> Updating Example Configuration

README.md, src/MiningCore/Blockchain/Bitcoin/BitcoinPayoutHandler.cs, src/MiningCore/Blockchain/Bitcoin/BitcoinPool.cs, src/MiningCore/Blockchain/Bitcoin/BitcoinProperties.cs, src/MiningCore/Blockchain/CoinMetaData.cs, src/MiningCore/Configuration/ClusterConfig.cs
Dears,
I've created a PR for Globaltoken(GLT) support by MiningCore
Regards,
John Ahn
=> Could you merge a Globaltoken(GLT) support by MiningCore?

src/MiningCore/Blockchain/CoinMetaData.cs
Dears,
There was a no **BLOCK** and **TX** information on https://bchain.info. 
So I was change them into following.
https://groestlsight.groestlcoin.org/block/
https://groestlsight.groestlcoin.org/tx/
Regards,
John Ahn
=> Groestl coin metadata update.

examples/zcash_pool.json
=> Update example configuration to include z-address.

src/MiningCore/Blockchain/CoinMetaData.cs, src/MiningCore/Blockchain/Ethereum/EthereumConstants.cs, src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs, src/MiningCore/Blockchain/Ethereum/EthereumPool.cs, src/MiningCore/Configuration/ClusterConfig.cs
When testing is not unlocked wallet you commented out these lines https://github.com/Konstantin35/miningcore/blob/4f291c0c521193ccad2550617fe800b8569a0c5f/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs#L396-L397 and unlock wallet in parity
=> Add support Ellaism

examples/ethereum_pool.json, src/MiningCore.Tests/Blockchain/Bitcoin/BitcoinJobTests.cs, src/MiningCore/Blockchain/Bitcoin/BitcoinJob.cs
hey there, coiniumserv author here :)
I've fixed a possible duplicate share exploit for your bitcoin-blockchain code (as detailed here: https://bitcointalk.org/index.php?topic=2035229.0). The other blockchain implementations may also need the fix.
I've also fixed a tiny typo in ethereum_pool.json.
=> fix for duplicate share exploit for bitcoin

README.md
I guess that Electroneum can be considered tested at this point in time since it is already running for quite a while now
=> Changed state of "Tested" for coin "Electroneum"

src/Miningcore/coins.json
=> Update Ravencoin explorer URL

examples/flo_pool.json, src/Miningcore/coins.json
Apply Flo re-branding to Miningcore
=> Florincoin -> Flo

src/Miningcore/Api/Controllers/PoolApiController.cs
=> Block Explorer Fix

src/Miningcore/Configuration/ClusterConfig.cs, src/Miningcore/Program.cs
Added SSL Support to Api Requests.
Added GZip Compression Support to Api Requests.
=> Added Api SSL Support

src/Native/libmultihash/equi/crypto/equihash.h
Fix the error in building equihashverify
=> Fix build error e.g. Ububtu 21.04

examples/monero_pool.json
This is a follow on from the comment i made in discord, hopefully this should help people get up and running until its fixed (if its a bug)
Stack trace of the exception causing this:
```[2021-07-27 19:59:04.1942] [E] [xmr] System.NullReferenceException: Object reference not set to an instance of an object.
at Miningcore.Blockchain.Cryptonote.CryptonoteJobManager.Configure(PoolConfig poolConfig, ClusterConfig clusterConfig) in /home/appveyor/projects/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonoteJobManager.cs:line 253
at Miningcore.Blockchain.Cryptonote.CryptonotePool.SetupJobManager(CancellationToken ct) in /home/appveyor/projects/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonotePool.cs:line 319
at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in …
```
=> [Examples] Add randomxRealm config option to the example

src/Miningcore/Miningcore.csproj
=> Update GitVersion.MsBuild 5.7.0

src/Miningcore/Blockchain/CoinMetaData.cs
=> Update CoinMetaData.cs (Bug)

src/Miningcore/Blockchain/Ergo/ErgoJobManager.cs
Add ConnectedPeers
Fix NetworkDifficulty
Fix NetworkHashrate
=> Update ErgoJobManager.cs (Fix)

build-debian-11.sh, build-ubuntu-20.04.sh, build-ubuntu-21.04.sh
You should update the package list after a new repo was added otherwise package wouldn't be found.
https://docs.microsoft.com/ru-ru/dotnet/core/install/linux-debian#install-the-sdk
=> Add repo update

src/Miningcore/coins.json
Hello,
please to add X11 - XRC to coin list in miningcore.
Thank you.
https://xrhodium.org/
=> Added XRC to coin list

src/Miningcore/Notifications/Messages/PaymentNotification.cs, src/Miningcore/Notifications/NotificationService.cs
This PR fixes a small typo in the payment notification.
=> fix: typo in payment notification

src/Miningcore/Api/Controllers/PoolApiController.cs
Configurable time window for fetching the top miners to allow more frequent updates of the top miners.
This implements the solution suggested by @Konstantin35 in #1333. 
It doesn't quite fix the issue though, as the hashrate still wont match the historical hashrate from `/api/pools/{poolid}/miners/{miner}/performance` but it allows a more frequent update of the top miners list.
=> feat: make top miners range configurable

src/Miningcore/Api/Controllers/PoolApiController.cs, src/Miningcore/Api/Responses/GetPoolsResponse.cs, src/Miningcore/Persistence/Postgres/Repositories/ShareRepository.cs, src/Miningcore/Persistence/Repositories/IShareRepository.cs
resolves https://github.com/oliverw/miningcore/discussions/963#discussioncomment-3814859
The code is ported from: https://github.com/GetBlok-io/miningcore/blob/master/src/Miningcore/Persistence/Postgres/Repositories/ShareRepository.cs#L203
=> feat: get current effort from pool

src/Miningcore/coins.json
small fixes to make maza and lcc work correctly.
=> Update coins.json for MAZA and LCC

.gitignore, README.md, miningcore.code-workspace, src/Miningcore.Tests/Crypto/HashingTests.cs, src/Miningcore/Blockchain/Ethereum/EthereumConstants.cs, src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs, src/Miningcore/Crypto/Hashing/Algorithms/Sha256DT.cs, src/Miningcore/Crypto/Hashing/Algorithms/Sha512256D.cs, src/Miningcore/Native/Multihash.cs, src/Miningcore/coins.json, src/Native/libmultihash/Makefile, src/Native/libmultihash/exports.cpp, src/Native/libmultihash/libmultihash.vcxproj, src/Native/libmultihash/libmultihash.vcxproj.filters, src/Native/libmultihash/sha256dt.c, src/Native/libmultihash/sha256dt.h, src/Native/libmultihash/sha256t.h, src/Native/libmultihash/sha512_256.c, src/Native/libmultihash/sha512_256.h
=> PinkChain / Novo / Radiant / EthOne integration 
